<?php
    $controller = 'page';

    $links = array(
        'familiespejd' => $this->url(array('controller' => $controller, 'action' => 'familiespejd')),
        'baever' => $this->url(array('controller' => $controller, 'action' => 'baever')),
        'ulve' => $this->url(array('controller' => $controller, 'action' => 'ulve')),
        'junior' => $this->url(array('controller' => $controller, 'action' => 'junior')),
        'trop' => $this->url(array('controller' => $controller, 'action' => 'trop')),
        'senior' => $this->url(array('controller' => $controller, 'action' => 'senior')),
        'rover' => $this->url(array('controller' => $controller, 'action' => 'rover'))
    );


?>

<div id="page" class="page">
    <div class="headline lefted">
        <p>
            Her i Herlufmagle gruppe er vores spejdere inddelt i nedenstående enheder.<br />
            Klik på enhedens logo for at læse mere om den pågældende enhed.
        </p>
        <div class="unit_list">
            <a href="<?php echo $links['familiespejd']; ?>" title="Læs mere om Familiespejd"><img src="../../images/unit_logos/familiespejd_logo.png" class="unit_list_logo" /></a>
            <table class="unit_details">
                <thead>
                    <th colspan="2">Familiespejder</th>
                </thead>
                <tr>
                    <td class="col">Aldersgruppe:</td>
                    <td>3-5 år (før-skole børn).</td>
                </tr>
                <tr>
                    <td>Mødetider:</td>
                    <td>Søndage, ca en gang om måneden.</td>
                </tr>
                <tr>
                    <td>Kontaktperson:</td>
                    <td>Torben Stenstrup</td>
                </tr>
                <tr>
                    <td></td>
                    <td><img src="../../images/icons/16x16/phone.png" class="icon16"/>3034 4620</td>
                </tr>
                <tr>
                    <td></td>
                    <td><img src="../../images/icons/16x16/email.png" class="icon16" />torben@topspejder.dk</td>
                </tr>
            </table>
        </div>
        <div class="unit_list">
            <a href="<?php echo $links['baever']; ?>" title="Læs mere om Bæverne"><img src="../../images/unit_logos/baever_logo.png" class="unit_list_logo" /></a>
            <table class="unit_details">
                <thead>
                    <th colspan="2">Bævere</th>
                </thead>
                <tr>
                    <td class="col">Aldersgruppe:</td>
                    <td>0. - 1. klasse.</td>
                </tr>
                <tr>
                    <td>Mødetider:</td>
                    <td>Tirsdage, 17.00 til 18.30.</td>
                </tr>
                <tr>
                    <td>Kontaktperson:</td>
                    <td>Vivi Engmark</td>
                </tr>
                <tr>
                    <td></td>
                    <td><img src="../../images/icons/16x16/phone.png" class="icon16"/>2491 1710</td>
                </tr>
                <tr>
                    <td></td>
                    <td><img src="../../images/icons/16x16/email.png" class="icon16" />vivi@topspejder.dk</td>
                </tr>
            </table>
        </div>
        <div class="unit_list">
            <a href="<?php echo $links['ulve']; ?>" title="Læs mere om Ulvene"><img src="../../images/unit_logos/ulv_logo.png" class="unit_list_logo" /></a>
            <table class="unit_details">
                <thead>
                    <th colspan="2">Ulve</th>
                </thead>
                <tr>
                    <td class="col">Aldersgruppe:</td>
                    <td>2. - 3. klasse,</td>
                </tr>
                <tr>
                    <td>Mødetider:</td>
                    <td>Tirsdage, 18.00 til 19.30.</td>
                </tr>
                <tr>
                    <td>Kontaktperson:</td>
                    <td>Mogens Engmark</td>
                </tr>
                <tr>
                    <td></td>
                    <td><img src="../../images/icons/16x16/phone.png" class="icon16"/>6170 0856</td>
                </tr>
                <tr>
                    <td></td>
                    <td><img src="../../images/icons/16x16/email.png" class="icon16" />mogens@topspejder.dk</td>
                </tr>
            </table>
        </div>
        <div class="unit_list">
            <a href="<?php echo $links['junior']; ?>" title="Læs mere om Juniorerne"><img src="../../images/unit_logos/junior_logo.png" class="unit_list_logo" /></a>
            <table class="unit_details">
                <thead>
                    <th colspan="2">Juniorspejdere</th>
                </thead>
                <tr>
                    <td class="col">Aldersgruppe:</td>
                    <td>4. - 5. klasse.</td>
                </tr>
                <tr>
                    <td>Mødetider:</td>
                    <td>Onsdage, 18.00 til 20.00.</td>
                </tr>
                <tr>
                    <td>Kontaktperson:</td>
                    <td>Helen Holm</td>
                </tr>
                <tr>
                    <td></td>
                    <td><img src="../../images/icons/16x16/phone.png" class="icon16"/>2089 5532</td>
                </tr>
                <tr>
                    <td></td>
                    <td><img src="../../images/icons/16x16/email.png" class="icon16" />helen@topspejder.dk</td>
                </tr>
            </table>
        </div>
        <div class="unit_list">
            <a href="<?php echo $links['trop']; ?>" title="Læs mere om Troppen"><img src="../../images/unit_logos/spejder_logo.png" class="unit_list_logo" /></a>
            <table class="unit_details">
                <thead>
                    <th colspan="2">Troppen (Claus Daa)</th>
                </thead>
                <tr>
                    <td class="col">Aldersgruppe:</td>
                    <td>6. - 7. klasse.</td>
                </tr>
                <tr>
                    <td>Mødetider:</td>
                    <td>Torsdage 19.00 til 21.00</td>
                </tr>
                <tr>
                    <td>Kontaktperson:</td>
                    <td>Dennis Kondrup</td>
                </tr>
                <tr>
                    <td></td>
                    <td><img src="../../images/icons/16x16/phone.png" class="icon16"/>4152 7270</td>
                </tr>
                <tr>
                    <td></td>
                    <td><img src="../../images/icons/16x16/email.png" class="icon16" />dennis@topspejder.dk</td>
                </tr>
            </table>
        </div>
        <div class="unit_list">
            <a href="<?php echo $links['senior']; ?>" title="Læs mere om Seniorerne"><img src="../../images/unit_logos/senior_logo.png" class="unit_list_logo" /></a>
                        <table class="unit_details">
                <thead>
                    <th colspan="2">Seniorspejdere</th>
                </thead>
                <tr>
                    <td class="col">Aldersgruppe:</td>
                    <td>8. - 17 år.</td>
                </tr>
                <tr>
                    <td>Mødetider:</td>
                    <td>Endnu ikke fastlagt</td>
                </tr>
                <tr>
                    <td>Kontaktperson:</td>
                    <td>Allan Bennermann</td>
                </tr>
                <tr>
                    <td></td>
                    <td><img src="../../images/icons/16x16/phone.png" class="icon16"/>2020 2814</td>
                </tr>
                <tr>
                    <td></td>
                    <td><img src="../../images/icons/16x16/email.png" class="icon16" />allan@topspejder.dk</td>
                </tr>
            </table>
        </div>
        <div class="unit_list">
            <a href="<?php echo $links['rover']; ?>" title="Læs mere om Roverne"><img src="../../images/unit_logos/rover_logo.png" class="unit_list_logo" /></a>
                        <table class="unit_details">
                <thead>
                    <th colspan="2">Rovere (Klan Valodia)</th>
                </thead>
                <tr>
                    <td class="col">Aldersgruppe:</td>
                    <td>18 år +</td>
                </tr>
                <tr>
                    <td>Mødetider:</td>
                    <td>Efter program</td>
                </tr>
                <tr>
                    <td>Kontaktperson:</td>
                    <td>Dennis Kondrup</td>
                </tr>
                <tr>
                    <td></td>
                    <td><img src="../../images/icons/16x16/phone.png" class="icon16"/>4152 7270</td>
                </tr>
                <tr>
                    <td></td>
                    <td><img src="../../images/icons/16x16/email.png" class="icon16" />dennis@topspejder.dk</td>
                </tr>
            </table>
        </div>
    </div>
</div>
