<?php
    $controller = 'page';

    $links = array(
        'familiespejd' => $this->url(array('controller' => $controller, 'action' => 'familiespejd')),
        'baever' => $this->url(array('controller' => $controller, 'action' => 'baever')),
        'ulve' => $this->url(array('controller' => $controller, 'action' => 'ulve')),
        'junior' => $this->url(array('controller' => $controller, 'action' => 'junior')),
        'trop' => $this->url(array('controller' => $controller, 'action' => 'trop')),
        'senior' => $this->url(array('controller' => $controller, 'action' => 'senior')),
        'rover' => $this->url(array('controller' => $controller, 'action' => 'rover'))
    );
    
    $units = array(
        array(
            'unitLogo' => "familiespejd_logo.png", 
            'unitName' => "Familiespejd", 
            'unitGroup' => "3-5 år (før-skole børn).", 
            'unitSchedule' => "Søndage, ca en gang om måneden.", 
            'unitContactName' => "Torben Stenstrup", 
            'unitContactPhone' => "3034 4620", 
            'unitContactEmail' => "torben@topspejder.dk",
            'unitPageLink' => $this->url(array('controller' => $controller, 'action' => 'familiespejd')),
            'unitPageTitle' => "Læs mere om Familiespejd"
        ),
        array(
            'unitLogo' => "baever_logo.png", 
            'unitName' => "Bævere", 
            'unitGroup' => "0. - 1. klasse.", 
            'unitSchedule' => "Tirsdage, 17.00 til 18.30.", 
            'unitContactName' => "Vivi Engmark", 
            'unitContactPhone' => "2491 1710", 
            'unitContactEmail' => "vivi@topspejder.dk",
            'unitPageLink' => $this->url(array('controller' => $controller, 'action' => 'baever')),
            'unitPageTitle' => "Læs mere om Bæverne"
        ),
        array(
            'unitLogo' => "ulv_logo.png", 
            'unitName' => "Ulve", 
            'unitGroup' => "2. - 3. klasse.", 
            'unitSchedule' => "Tirsdage, 18.00 til 19.30.", 
            'unitContactName' => "Mogens Engmark", 
            'unitContactPhone' => "6170 0856", 
            'unitContactEmail' => "mogens@topspejder.dk",
            'unitPageLink' => $this->url(array('controller' => $controller, 'action' => 'ulve')),
            'unitPageTitle' => "Læs mere om Ulvene"
        ),
        array(
            'unitLogo' => "junior_logo.png", 
            'unitName' => "Juniorspejdere", 
            'unitGroup' => "4. - 5. klasse.", 
            'unitSchedule' => "Onsdage, 18.00 til 20.00.", 
            'unitContactName' => "Helen Holm", 
            'unitContactPhone' => "2089 5532", 
            'unitContactEmail' => "helen@topspejder.dk",
            'unitPageLink' => $this->url(array('controller' => $controller, 'action' => 'junior')),
            'unitPageTitle' => "Læs mere om Juniorspejderne"
        ),
        array(
            'unitLogo' => "spejder_logo.png", 
            'unitName' => "Tropspejdere (Claus Daa)", 
            'unitGroup' => "6. - 7. klasse.", 
            'unitSchedule' => "Torsdage, 19.00 til 21.00.", 
            'unitContactName' => "Dennis Kondrup", 
            'unitContactPhone' => "4152 7270", 
            'unitContactEmail' => "dennis@topspejder.dk",
            'unitPageLink' => $this->url(array('controller' => $controller, 'action' => 'trop')),
            'unitPageTitle' => "Læs mere om Troppen"
        ),
        array(
            'unitLogo' => "senior_logo.png", 
            'unitName' => "Seniorspejdere", 
            'unitGroup' => "8. klasse til 17 år.", 
            'unitSchedule' => "Torsdage, 19.00 til 21.00.", 
            'unitContactName' => "Allan Bennermann", 
            'unitContactPhone' => "2020 2814", 
            'unitContactEmail' => "allan@topspejder.dk",
            'unitPageLink' => $this->url(array('controller' => $controller, 'action' => 'senior')),
            'unitPageTitle' => "Læs mere om Seniorerne"
        ),
        array(
            'unitLogo' => "rover_logo.png", 
            'unitName' => "Rovere (Klan Valodia)", 
            'unitGroup' => "18 år +", 
            'unitSchedule' => "Efter program.", 
            'unitContactName' => "Dennis Kondrup", 
            'unitContactPhone' => "4152 7270", 
            'unitContactEmail' => "dennis@topspejder.dk",
            'unitPageLink' => $this->url(array('controller' => $controller, 'action' => 'rover')),
            'unitPageTitle' => "Læs mere om Roverne"
        )
    );


?>

<div id="page" class="page">
    <div class="headline lefted">
        <p>
            Her i Herlufmagle gruppe er vores spejdere inddelt i nedenstående enheder.<br />
            Klik på enhedens logo for at læse mere om den pågældende enhed.
        </p>
<?php
    foreach($units as $unit) {
?>        
        <div class="unit_list">
            <a href="<?php echo $unit['unitPageLink']; ?>" title="<?php echo $unit['unitPageTitle'] ?>"><img src="../../images/unit_logos/<?php echo $unit['unitLogo'] ?>" class="unit_list_logo" /></a>
            <table class="unit_details">
                <thead>
                    <th colspan="2"><?php echo $unit['unitName'] ?></th>
                </thead>
                <tr>
                    <td class="col">Aldersgruppe:</td>
                    <td><?php echo $unit['unitGroup'] ?></td>
                </tr>
                <tr>
                    <td>Mødetider:</td>
                    <td><?php echo $unit['unitSchedule'] ?></td>
                </tr>
                <tr>
                    <td>Kontaktperson:</td>
                    <td><?php echo $unit['unitContactName'] ?></td>
                </tr>
                <tr>
                    <td></td>
                    <td><img src="../../images/icons/16x16/phone.png" class="icon16"/><?php echo $unit['unitContactPhone'] ?></td>
                </tr>
                <tr>
                    <td></td>
                    <td><img src="../../images/icons/16x16/email.png" class="icon16" /><?php echo $unit['unitContactEmail'] ?></td>
                </tr>
            </table>
        </div>
<?php
    }
?>

    </div>
</div>
