<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
?>

<div id="page" class="page">
    <div id="unitDescriptionHeader">
        <img class="unitDetailsLogo" src="../../images/unit_logos/familiespejder_farve_stor.png">
        <h1>Familiespejd</h1>
    </div>

Hvad er FamilieSpejd? 

Vi er en stribe børnefamilier der mødes cirka en søndag 
hver måned for at lave sjove aktiviteter fra kl. 10 til 13.

Aktiviteterne retter sig mod familiens 3-5 årige børn og 
forældre samt søskende. De 3-5 årige meldes ind i 
spejdergruppen og betaler 250 kr. pr. kvartal i kontingent. 
Barnets kontingentbetaling dækker også for forældre og 
søskende (som ikke er spejdere).

Vi holder til på spejdergrunden på Sletskovvej 5 og vi er 
udendørs, så husk altid påklædning efter vejret.

Vi bruger bålet som ramme for vores fællesskab og laver 
tit lidt lækkert på bålet (pandekager, frugt, brød, pizza og
endda røgede sild). Vores aktiviteter handler om natur, 
friluftsliv og lege. Vi hedder Rumpenisserne og har det
sjovt i skoven ligesom Ronja Røverdatter – vi har også en 
Rumpenissesang, vi synger hver gang vi er samlet.

Har du spørgsmål er du velkommen til at kontakte Torben
Stenstrup på tlf. 30344620 eller mail: torben@topspejder.dk. 

Der er ingen tilmelding – bare mød op.

Torben Stentrop
Helen Holm

Anne-Mette Nielsen
Camilla Crone


</div>