<div id="page" class="page">
	<div class="headline lefted"><h2>Spejdergruppe med fuld fart</h2></div>
    <h4>
    	<p>Vi er en spejdergruppe i vækst og udvikling på mange forskellige punkter. Vi har cirka 100 medlemmer, hvoraf langt de fleste er børn og unge, som understøttes af mange engagerede og kompetente voksne ledere.</p> 
    	<p>Vi har en god opbakning i vores lokalsamfund og turen til Tunesien har været medvirkende til, at mange forældre, familier og nøglepersoner i vores område, støtter op om vores aktiviteter.</p>
        <p>Vi værdsætter kvalitet, mening med vores aktiviteter, et tværgående fællesskab i Herlufmagle og Gelsted. Og så skal det væres sjovt, udfordrende og udviklende for det enkelte barn, den unge eller den frivillige spejderleder samtidig!</p>
        <p>Følg med her på hjemmesiden og læs mere om vores forskellige aktiviteter og projekter når de kommer op - og får du lyst til at opleve det i praksis er der også en plads til dig!</p>
</h4>
    
    <div class="headline lefted"><h2>Hvordan hænger det hele sammen</h2></div>
    <h4>
    	<p><b>Gruppen:</b><br>Herlufmagle Gruppe er opdelt i enheder med en aldersgruppe af børn og en ansvarlig leder - det er bæverne, ulvene, Claus Daa, seniorspejderne og roverklanen.</p>
		<p>Alle lederne udgør i fællesskab et lederteam og har udpeget en gruppeleder, som sammen med to assistenter forestår den løbende koordinering af gruppens aktiviteter og ledernes personlige udvikling.</p>
		<p>Spejdergruppen er en forening i Næstved Kommune og ledes af et Grupperåd (bestyrelse) som består af en række forældrevalgte repræsentanter, en repræsentant for de over 17-årige spejdere, gruppens kasserer og endelig gruppelederen og enhedslederne.</p>
		<p>Hvert år i februar måned holdes Gruppemødet (generalforsamling) som er foreningens øverste myndighed i henhold til foreningens vedtægter.</p>
		<br>
		<p><b>Lokalt:</b><br>Herlufmagle Gruppe er ligesom ca. 25 andre foreninger i Næstved Kommune organiseret i Børne- og Ungdomsorganisationernes Samråd (BUS) som mødes flere gange om året og varetager spejdernes, FDF'ernes og andre ungdomsorganisationers interesser overfor Næstved Kommune og Folkeoplysningsudvalget.</p>
		<p>Deruover er de 22 KFUM-Spejdergrupper i vores område organiseret i Suså Distrikt, som står for uddannelse, fælles aktiviteter og understøtter grupper der har brug for en hjælpende hånd.</p> 
 		<br>
		<p><b>Landsdækkende:</b><br>Vi er en lokal gruppe i landsorganisationen KFUM-Spejderne i Danmark, som har knap 25.000 medlemmer. KFUM-Spejderne i Danmark (korpset) har en Hovedbestyrelse på 11 personer og et sekretariat bemandet med lønnede kræfter. Du kan læse mere om KFUM-Spejderne i Danmark på <a href="http://www.spejdernet.dk">www.spejdernet.dk</a></p>
		<br>
		<p><b>Internationalt:</b><br>På verdensplan er vi medlem af Verdensspejderbevægelsen (WOSM) der har mere end 28 millioner medlemmer over hele kloden. Spejderbevægelsen blev stiftet i 1907 af Lord Robert Baden-Powell og fejrede således i 2007 sit 100 års jubilæum. Du kan læse mere om Verdensspejderbevægelsen på <a href="http://www.scout.org">www.scout.org</a></p>
    </h4>
    
    
    <div class="author_tag">27-4-2011 - Mogens Engmark</div>
</div>	