<div id="page" class="page">
	<div class="headline lefted"><h2>Kontaktoplysninger mv</h2></div>
    <h4>
    	<p>
            <b>Gruppeleder:</b><br />
            Torben Stenstrup<br />
            <img src="../../images/icons/16x16/email.png" class="icon16" />torben@topspejder.dk
        </p>
    	<p>
            <b>Grupperådsformand:</b><br />
            Claus Ladegaard<br />
            <img src="../../images/icons/16x16/email.png" class="icon16" />formand@topspejder.dk
        </p>
    	<p>
            <b>Kasserer:</b><br />
            Torben Larsen<br />
            <img src="../../images/icons/16x16/email.png" class="icon16" />kasserer@topspejder.dk
        </p>
    	<p>
            <b>Hjemmeside:</b><br />
            Mogens Engmark<br />
            <img src="../../images/icons/16x16/email.png" class="icon16" />mogens@topspejder.dk
        </p>
    	<p>
            <b>Kirkeblade:</b><br />
            Jette Juul<br />
            <img src="../../images/icons/16x16/email.png" class="icon16" />kirkeblade@topspejder.dk
        </p>
    </h4>

    <div class="author_tag">22-08-2012 - Mogens Engmark</div>
</div>