<div id="page" class="page">
	<div class="headline lefted"><h2>Kontaktoplysninger mv</h2></div>
    <h4>
    	<p><b>Gruppeleder:</b><br>Torben Stenstrup<br>Email: torben@topspejder.dk</p>
    	<p><b>Grupperådsformand:</b><br>Claus Ladegaard<br>Email: formand@topspejder.dk</p>
    	<p><b>Kasserer:</b><br>Torben Larsen<br>Email: kasserer@topspejder.dk</p>
    	<p><b>Hjemmeside:</b><br>Mogens Engmark<br>Email: mogens@topspejder.dk</p>
    </h4>

    <div class="author_tag">01-05-2012 - Mogens Engmark</div>
</div>