<div id="page" class="page">
	<div class="headline lefted"><h2>Kontaktoplysninger mv</h2></div>
    <h4>
    	<p><b>Gruppeleder:</b><br>Torben Stenstrup<br>Email: torben@topspejder.dk</p> 
    	<p><b>Kasserer:</b><br>Stig Keller<br>Email: kasserer@topspejder.dk</p> 
    	<p><b>Hjemmeside:</b><br>Mogens Engmark<br>Email: mogens@topspejder.dk</p> 
    </h4>
    
    <div class="author_tag">27-4-2011 - Mogens Engmark</div>
</div>	