<?php
?>

<div id="page" class="page">
    <div class="headline lefted"><h2>Mødetider for spejderne</h2></div>
    <h4>
        Her er en hurtig oversigt over de forskellige enheders mødetider. For kontaktinformationer se under "Enhederne".
        <table>
            <tr>
                <td>Familespejdere</td>
                <td>3-5 år</td>
                <td>En søndag om måneden - se mere under "Enhederne" -> "Familiespejder"</td>
            </tr>
            <tr>
                <td>Bævere</td>
                <td>0. -  1. klasse</td>
                <td>Tirsdage, 17.00 - 18.30</td>
            </tr>
            <tr>
                <td>Ulve</td>
                <td>2. -  3. klasse</td>
                <td>Tirsdage, 18.00 - 19.30</td>
            </tr>
            <tr>
                <td>Juniorer</td>
                <td>4. -  5. klasse</td>
                <td>Onsdage, 18.00 - 20.00</td>
            </tr>
            <tr>
                <td>Claus Daa</td>
                <td>6. -  7. klasse</td>
                <td>Torsdage, 19.00 - 21.00</td>
            </tr>
            <tr>
                <td>Seniorer</td>
                <td>8. - 10. klasse</td>
                <td>Torsdage, 19.00 - 21.00</td>
            </tr>
            
        </table>
        <p>Vi glæder os til at se jer!</p>
    </h4>
    <div class="author_tag">22-08-2012 - Mogens Engmark</div> 
    <br />
        <div class="headline lefted"><h2>Oprykning, tirsdag 21-8-2012, klokken 18.30 - 20.30</h2></div>
    <h4>
        <p>
            Nu nærmer sig tiden, hvor vi skal til at uddele årsstjerner og spejderne rykker mellem enhederne. *)
        </p>
        <p>
            Så <b>HUSK</b> at møde op på tirsdag og få din årsstjerne - det vil også være super godt om vi kunne få så mange som muligt med på årets gruppebillede.
        </p>
        <p>
            <b>BEMÆRK:</b> Der vil ikke være almindelige møder for Bævere, Ulve, Juniorer eller Claus Daa i denne uge.
        </p>
        <p>Spørgsmål og/eller andet til Torben Stenstrup : tlf. 3034 4620 - mail : torben@topspejder.dk</p>
    </h4>
    <p>
        <i>*) Dem der er begyndt i 0. klasse skal være bævere, 2. klasse skal være ulve, 4. klasse skal være juniorspejdere, 6. klasse skal være Claus Daa spejdere og 8. klasse + en god flok skal etablere en ny seniorspejdertrop.</i>
    </p>
    <h4>
        <p>Vi glæder os til at se jer!</p>
        <p>Spejderhilsen fra lederne i Herlufmagle Gruppe</p>
    </h4>
    <div class="author_tag">16-08-2012 - Mogens Engmark</div> 
    <br />
    <div class="headline lefted"><h2>Ny mødetid for Juniorerne</h2></div>
    <h4>
        <p>
            Mødetidspunktet for Juniorspejderne er her efter sommerferien ændret, således at det nu er <b>Onsdage, klokken 18.00 til 20.00</b>.
        </p>
    </h4>
    <div class="author_tag">16-08-2012 - Mogens Engmark</div> 
    <br />
    <div class="headline lefted"><h2>Så er sommerferien slut...</h2></div>
    <h4>
        <p>
            ... og vi er i gang igen :)<br />
            Sommeren har budt på mange spejderaktiviteter - Bæverlejr på Stevns, Ulvelejr i Kværkeby, Aktive feriedage i Næstved og ikke mindst Spejdernes Lejr 2012, bare for at tage nogle af overskrifterne.<br />
        </p>
        <p>
            2. halvår 2012 kommer også til at byde på en masse spændende aktiviteter og arrangementer, så vi kommer ikke til at ligge stille.<br />
            Hjemmesiden her har også fået et lille løft - vores gruppeleder Torben Stenstrup har skrevet lidt nyt "Om gruppen" - og der kommer noget mere information omkring enheder, mødetider osv.
        </p>
        <p>Spejderhilsen</p>
        <p>    
           Mogens Engmark 
        </p>
    </h4>
    <div class="author_tag">16-08-2012 - Mogens Engmark</div>    
<?php /** ?>  
	<div class="headline lefted"><h2>Juniorerne sejrede i "Kampen om Næsby"</h2></div>
	<h4>
		<p>
			<table width="100%">
				<tr>
					<td>
            			Det var en flok meget stolte juniorer, der tog hjem fra Næsbycenteret som "de sande herskere over centret" efter at have deltaget i juniorweekenden.<br>
            			Der blev dystet i mangt og meget - lige fra konstruktion af blider til at lave en "romantisk middag for to", herunder naturligvis også borddækning (Og hvad andet gør man, end selvfølgelig at pionere en brødkurv til anledningen?)<br>
            			En super flot førsteplads blev det til og de stolte spejdere kunne tage trofæet, en flot økse med lejrens mærke, med hjem.
        			</td>
					<td width="135" class="righted">
						<img src="images/kampen_om_naesby.jpg" width="125" />
					</td>
				</tr>
			</table>
		</p>
		<!--  <h5>Se billeder fra dagen <a href="https://picasaweb.google.com/113933098347309535962/DistriktsturneringBVereOgUlve2012?authuser=0&authkey=Gv1sRgCNzmgYXnkJQL&feat=directlink" target="blank">her</a>.</h5> -->
	</h4>
	<div class="headline lefted"><h2>Distriktsturnering for Bævere og Ulve 2012</h2></div>
	<h4>
		<p>
			<table width="100%">
				<tr>
					<td>
            			Ca. 80 friske bævere og ulve stillede til Distriktsturneringen for Bævere og Ulve, som vi afholdt sammen med Distriktet i Glumsø. Herlufmagle stillede med ca. 25 spejdere, to bæverfamilier og tre ulvebander, der sammen med spejderne fra resten af distriktet skulle hjælpe Spejderman mod hans nemesis Dr. Skurk.<br>
            			Det var en super dag med spændende poster hvor spejderne kom gennem store dele af verdenen.<br>
            			Skælskør Gruppe's bævere løb med sejren for Bæverne og en af Herlufmagles bander tog trofæet med hjem til Ulvene.
					</td>
					<td width="370" class="righted">
						<img src="images/ulve-distriktsturnering.jpg" width="360" />
					</td>
				</tr>
			</table>
		</p>
		<h5>Se billeder fra dagen <a href="https://picasaweb.google.com/113933098347309535962/DistriktsturneringBVereOgUlve2012?authuser=0&authkey=Gv1sRgCNzmgYXnkJQL&feat=directlink" target="blank">her</a>.</h5>
	</h4>
   	<div class="author_tag">01-05-2012 - Mogens Engmark</div>
	<div class="headline lefted"><h2>Arbejdsaften og forældremøde om Spejdernes Lejr d. 14. maj</h2></div>
	<h4>
		<p>
			Vi håber, at vi igen i år kan samle de 50-60 børn og voksne som vi plejer at være til denne hyggelige dag.<br>
			Klokken 16.30 starter vi på forårsklargøringen af vores hytte og udendørsområderne, vi skal blandt andet have givet bålpladsen og området omkring den et facelift.<br>
			Omkring klokken 19.00 byder vi traditionen tro på et måltid mad til de flittige arbejdsfolk.<br><br>Fra klokken 19.30 til 20.30 holder vi et informationsmøde for Junior og Claus Daa spejdere omkring "Spejdernes Lejr", hvor der selvfølgelig kan stilles spørgsmål til lejren.
		</p>
		<h5>Læs mere om dagens program <a href="files/Arbejdsdag_maj_2012_og_forældremøde.pdf" target="blank">her</a>.</h5>
	</h4>
   	<div class="author_tag">01-05-2012 - Mogens Engmark</div>
	<div class="headline lefted"><h2>Spejderman til Distriktsturneringen for Bævere og Ulve</h2></div>
	<h4>
		<p>
			<table width="100%">
				<tr>
					<td>
            			Lørdag d. 28-4 2012 er der Distriktsturnering for Bævere og Ulve i Glumsø.<br><br>Vi skal ud og hjælpe Spejderman mod hans nemisis, den onde dr. Skurk, der har skumle planer. Vi mødes ved Spejderhytten i Glumsø, Stendyssevej 12, 4171 Glumsø, klokken 9.15 og det slutter igen klokken 16.00.<br><br>
            			Vi laver mad på bål, så I skal <b>ikke</b> have madpakke med. Sørg for at have tøj på der passer til vejret, en kop med navn på og papir og blyant i lommen.
        			</td>
        			<td width="175" class="righted">
						<img src="images/distriktsturnering2012.jpg" width="160" />
					</td>
				</tr>
			</table>
		</p>
		<!--  <h5>Læs mere om dagens program <a href="files/BUSK_30102011.pdf" target="blank">her</a>.</h5> -->
	</h4>
   	<div class="author_tag">15-04-2012 - Mogens Engmark</div>
	<div class="headline lefted"><h2>Juniorer til "Kampen om Næsby"</h2></div>
	<h4>
		<p>
			Den 27-4 drager Juniortroppen til Næsby for at deltage i "Kampen om Næsby"<br>
			Der skal dystes mod spejder fra mange andre grupper i forskellige dicipliner, så hvem ved? Måske kan Juniorerne erobre den største del af Næsbycenteret og løbe med sejren?
		</p>
		<!--  <h5>Læs mere om dagens program <a href="files/BUSK_30102011.pdf" target="blank">her</a>.</h5> -->
	</h4>
   	<div class="author_tag">15-04-2012 - Mogens Engmark</div>
	<div class="headline lefted"><h2>Claus Daa til DM i spejd</h2></div>
	<h4>
		<p>
			Claus Daa spejderne deltog i årets kvalifikations runde til Danmarks Mesterskabet i Spejder, der blev afholdt på Næsby Centeret d. 23-25 marts.<br>
			Desværre lykkedes det ikke troppen at kvalificere sig til finalen, men spejderne selv syntes, at det var en af de fedeste oplevelser de har haft.
		</p>
		<!--  <h5>Læs mere om dagens program <a href="files/BUSK_30102011.pdf" target="blank">her</a>.</h5> -->
	</h4>
   	<div class="author_tag">15-04-2012 - Mogens Engmark</div>
	<div class="headline lefted"><h2>Nyt nyhedsbrev ude..</h2></div>
	<h4>
		<p>
			Så er der nyt fra fronten..  :)<br>
			Læs lidt mere om Lodsedler, Arbejdsdag og Spejdernes Lejr og gruppens sommerlejr i 2013.
		</p>
		<h5>Til dem der ikke har fået det på mail eller ikke lige kan finde den, så kan det også hentes <a href="files/NyhedsbrevApril2012.pdf" target="blank">her</a>.</h5>
	</h4>
   	<div class="author_tag">15-04-2012 - Mogens Engmark</div>
	<div class="headline lefted"><h2>Sommerlejr for Ulvene</h2></div>
	<h4>
		<p>
			Ulvenes sommerlejr ligger i år fra d. 2-7 til d. 6-7.<br>
			Vi skal til Bjerghytten der ligger ved Kværkeby. Husk at udfylde en forhåndstilmelding og aflevere den til Baloo eller Pudmini.
		</p>
		<!--  <h5>Læs mere om dagens program <a href="files/BUSK_30102011.pdf" target="blank">her</a>.</h5> -->
	</h4>
   	<div class="author_tag">15-04-2012 - Mogens Engmark</div>
	<div class="headline lefted"><h2>Sommerlejr for Bæverne</h2></div>
	<h4>
		<p>
			Bæverne skal i år skal på Dino-lejr ved Stevns Klint sammen med bæverne fra Glumsø gruppe.<br>
			Lejren varer fra d. 29-6 til 1-7.
		</p>
		<!--  <h5>Læs mere om dagens program <a href="files/BUSK_30102011.pdf" target="blank">her</a>.</h5> -->
	</h4>
   	<div class="author_tag">15-04-2012 - Mogens Engmark</div>
	<!--
	<div class="headline lefted"><h2>BUSK gudstjeneste søndag d. 30-10-2011</h2></div>
	<h4>
		<p>
			Søndag d. 30-10-2011 klokken 10.00 er der Børn, Unge, Sogn og Kirke gudstjeneste i Herlufmagle Kirke.<br>
			Herefter går vi ned til hytten, hvor vi vil hygge os i enhederne og lave nogle forskellige aktiviteter et par timer.<br>
			Vi glæder os til at se en masse spejdere og familier på en dejlig efterårsdag.
		</p>
		<h5>Læs mere om dagens program <a href="files/BUSK_30102011.pdf" target="blank">her</a>.</h5>
	</h4>
   	<div class="author_tag">27-10-2011 - Mogens Engmark</div>
	<div class="headline lefted"><h2>Juletur med Asterix og Obelix</h2></div>
	<h4>
		<p>
			Vores traditionsrige juletur går i år til Bisserup Lejren, d. 25-27 november.<br>
			Vi skal på jagt efter trylledrik, deltage i Gallernes Olympiske Lege, holde Vildsvineædegilde og meget mere.<br>
		</p>
		<h5>Læs mere om turen <a href="files/Juletur_2011.pdf" target="blank">her</a> og om hvad du skal have med.</h5>
	</h4>
   	<div class="author_tag">27-10-2011 - Mogens Engmark</div>

	<div class="headline lefted"><h2>Spejdernes Lejr 2012</h2></div>
	<h4>
		<p>
			Nu nærmer sig den største spejderlejr på dansk jord. Fra d. 21. til den 29 juli, 2012 samles spejdere fra alle 5 spejderkorps i Holstebro.<br>
			Fra Herlufmagle er det junior- og Claus Daa-spejderne der skal afsted og bo i samme kvarter med alle de andre spejdere fra Næstved Kommune.<br>
			For at hjælpe arrangørerne med at få et bedre overblik i planlægningen af lejren, er det nødvendigt vi forhåndsregistrer os. Det er derfor vigtigt at du afleverer tilmeldingen til din leder senest 27-11-2011.
		</p>
		<h5>Tilmeldingsblanket og mere information findes <a href="files/SpejdernesLejrTilmelding.pdf" target="blank">her</a>.</h5>
	</h4>
   	<div class="author_tag">27-10-2011 - Mogens Engmark</div>

	<div class="headline lefted"><h2>Åbent Landbrug - 2011</h2></div>
	<h4>
		<div id="video"><iframe width="420" height="315" src="http://www.youtube.com/embed/iSmE3oE7qiU" frameborder="0"></iframe></div>
		<p>
			Søndag d. 18-9-2011 blev der afholdt Åbent Landbrug over hele landet og Herlufmagle Gruppe var igen i år med på <a href="http://www.aabentlandbrug.dk/Find_gaard/Sjaelland_og_Sydhavsoerne/Assendrup_Hovedgaard.aspx" target="blank">Assendrup Hovedgård</a>.<br />
			1300 mennesker trodsede vind og vejr, besøgte gårdens køer og kom "Tættere på Naturen" med vores mangfoldige aktiviteter.<br />
			<br />
			<br />
			I år kunne vi byde på:
			<ul>
				<li>Abebro og forhindringsbane</li>
				<li>To bordfodboldbaner med 24 bigballer halm til 2x6 spillere</li>
				<li>Kraniequiz med 8 forskellige dyrekranier</li>
				<li>Knoglepuslespil – saml en ræv</li>
				<li>Gæt et gevir med opsats fra Kronhjort, Då, Rå og Sikahjort</li>
				<li>Karla Ko brændemærke på læderlap</li>
				<li>Snitteværksted på rensdyrskind</li>
				<li>Naturpuslespil med Karla Ko (se videoen til højre)</li>
				<li>Kig i et patruljetelt</li>
			</ul>
			<br />
			For os i Herlufmagle Gruppe var det en spændende dag med masser af besøg af nysgerrige børn og voksne, gode oplevelser i det fri og en masse sjov og ballade.<br />
		</p>
		<table width="100%">
			<tr>
				<td width="25%" class="topped centered"><img src="images/aaben_landbrug_DSC_1023.jpg"></td>
				<td width="25%" class="topped centered"><img src="images/aaben_landbrug_DSC_1031.jpg"></td>
				<td width="25%" class="topped centered"><img src="images/aaben_landbrug_DSC_1045.jpg"></td>
				<td width="25%" class="topped centered"><img src="images/aaben_landbrug_DSC_0033.jpg"></td>
			</tr>
		</table>
		<p>Ses vi igen til næste år?</p>
    </h4>
   	<div class="author_tag">21-9-2011 - Mogens Engmark</div>
	<div class="headline lefted"><h2>Familiespejd - en ny enhed</h2></div>
	<h4>
		<p>Den 25-9-2011 klokken 10.00 starter vi en ny enhed op i Herlufmagle Gruppe. FamilieSpejd, som denne nye enhed hedder til et tilbud til børn i alderen 3-5 år og deres familier. Så hvis friluftsliv og naturoplevelser er noget der tiltaler jer, så klæd jer på efter vejret og kig forbi.</p>
		<h5>I <a href="files/FamilieSpejd.pdf" target="blank">denne</a> folder kan du også finde lidt mere information</h5>
    </h4>
   	<div class="author_tag">30-8-2011 - Mogens Engmark</div>
	<div class="headline lefted"><h2>Suså Idrætsdag 2011</h2></div>
	<h4>
		<p>Vejret holdt tørt og lokkede ca. 300 mennesker til Herlufmagle Hallen, som dannede ramme for Suså Idrætsdag 2011.</p>
		<p>Mange var forbi spejdernes stand og klatre på vores abebro og spille bordfodbold.</p>
		<h5>Der blev også taget en masse <a href="https://picasaweb.google.com/113933098347309535962/SusaIdrTsdag?authuser=0&authkey=Gv1sRgCLOs2IGag5bIdQ&feat=directlink" target="blank">billeder</a> og en <a href="http://www.youtube.com/watch?v=i7TdpKLQuLc" target="blank">video</a> blev det sørme også til</h5>
    </h4>
   	<div class="author_tag">30-8-2011 - Mogens Engmark</div>
	<div class="headline lefted"><h2>Billeder fra oprykningsdagen</h2></div>
	<h4>
		<p>En skøn dag med masser af sol og glade spejdere lagde rammen for vores oprykningdag. Demos Cratos gav motion og sved på panden hos mange, og den lækre, bålstegte flæskesteg blev indtaget med velbehag.</p>
		<p>Der blev også uddelt en masse stjerner - løst regnet var der stjerner for 411 spejderår.</p>
		<h5>Der blev også taget en masse billeder - se <a href="https://picasaweb.google.com/113933098347309535962/Oprykning2011?authuser=0&authkey=Gv1sRgCNr73v_YhcHZTg&feat=directlink" target="blank">HER</a> for at (gen)opleve arrangemetet</h5>
    </h4>
   	<div class="author_tag">28-8-2011 - Mogens Engmark</div>
   	 -->
   	<!--
	<div class="headline lefted"><h2>Oprykningsdag d. 21-8-2011 Klokken 10.00 - 15.00</h2></div>
	<h4>
		<p>En af de store traditioner i Herlufmagle Gruppe er oprykningsdagen der altid ligger 21. august. I år er det en søndag og derfor vil vi gøre lidt særligt ud af den.</p>
		<table width="100%">
			<tr>
				<td><b>Program</b></td>
				<td width="10"></td>
				<td></td>
			</tr>
			<tr>
				<td>10.00</td>
				<td></td>
				<td>Familiegudstjenste i Herlufmagle Kirke</td>
			</tr>
			<tr>
				<td>11.00</td>
				<td></td>
				<td>Vi mødes ved hytten, velkomst</td>
			</tr>
			<tr>
				<td>11.15</td>
				<td></td>
				<td>Demos Cratos - Spillet som Seniorspejderne udviklede sammen med tuneserne til SEE20:10</td>
			</tr>
			<tr>
				<td>13.00</td>
				<td></td>
				<td>Bålmad til alle (30,- kroner pr. pers. incl. sodavand - betales på dagen)</td>
			</tr>
			<tr>
				<td>14.15</td>
				<td></td>
				<td>Oprykningscerimoni og uddeling af Årsstjerner</td>
			</tr>
			<tr>
				<td>15.00</td>
				<td></td>
				<td>Tak for i dag.</td>
			</tr>
		</table>
		<p>Der er ingen tilmelding til oprykningsdagen – mød blot frem. Vil I være med til at spise bålmad, betaler I blot på dagen.</p>
		<h3 class="centered"><b>HUSK</b> at kun de medlemmer der personligt møder frem <b>kl. 14.15 – 15.00</b> får overrakt årsstjerner til uniformen.</h3>


		<h5>Programmet for den store dag kan hentes <a href="files/Oprykning2011.pdf" target="blank">HER</a></h5>
    </h4>
   	<div class="author_tag">3-8-2011 - Mogens Engmark</div>
   	<br />
    <div class="headline lefted"><h2>Nyt nyhedsbrev er ude</h2></div>
	<h4>
		<p>Vores gruppeleder har begået et nyt nyhedsbrev. Læs de seneste nyheder og se lidt om hvad der skal ske det næste stykke tid.</p>
		<h5>Det kan hentes <a href="files/NyhedsbrevAugust2011.pdf" target="blank">HER</a></h5>
    </h4>
   	<div class="author_tag">3-8-2011 - Mogens Engmark</div>
   	<br />
    <div class="headline lefted"><h2>Ulvenes heks blev sendt til Bloksbjerg</h2></div>
   	<h4>
		<table>
			<tr>
				<td>
					<p>Trods truende skyer og byger fandt mange vej til spejdergrunden med medbragt mad og godt humør. Næstved Brand og Redning lavede skumbad til alle der havde lyst, og igen i år kan vi takke Herlufmagle Auto for sponsering af skummet. Ved bålet lavede børnene massevis af pandekager og dejlige popcorn. Flere børn tog også udfordringen op i spejdernes vandrette bungee jump bane, hvor man bliver trukket ud i en lang cykelslange og skudt henover en presenning med vand og brun sæbe…</p>
					<p>Årets båltaler var Knud Erik Antonsen og imens knitrede bålet lystigt, hvilket var en overraskelse for mange, eftersom regnen havde høvlet ned de to foregående døgn. Men spejdere kan altså tænde bål og i løbet af kort tid røg ulvenes kunstfærdigt udførte heks til Bloksbjerg.</p>
					<p>Tak for det gode fremmøde og især en stor tak til de mange lokale erhvervsdrivende, der havde givet flotte og mange præmier til vores amerikanske lotteri:</p>
					<table width="100%">
						<tr>
							<td width="50%">
								<ul>
									<li>Alcon´s Fitness</li>
									<li>1X2 Biler</li>
									<li>Body & Soul</li>
									<li>Daglig Brugsen Gelsted</li>
									<li>Landsbyhuset</li>
									<li>Nærkøb - Buketten</li>
									<li>Wulff Auto</li>
									<li>JHF transport</li>
									<li>Bygge og anlægsentreprenør</li>
									<li>Rune Nielsen</li>
									<li>Carlssons VVS</li>
									<li>Jensen Køleteknik</li>
									<li>A/S Sjællandske Medier</li>
									<li>Fætter BR i Næstved</li>
									<li>Gitte Sass Briller</li>
									<li>Inter Sport</li>
									<li>Pingel Cykler</li>
									<li>Spejdersport</li>
									<li>Elektrogården</li>
									<li>DT Autoteknik</li>
									<li>Frugtpresse.dk</li>
									<li>Vognmand Stig Hansen</li>
									<li>El Huset Glumsø</li>
									<li>Glumsø Bogtrykkeri A/S</li>
									<li>Ib Nordmark VVS</li>
								</ul>
							</td>
							<td width="50%">
								<ul>
									<li>Wengbergs Møbler</li>
									<li>Diba</li>
									<li>Estate Mæglerne A/S</li>
									<li>Ropox</li>
									<li>Stiegs Auto</li>
									<li>Ringsted Apotek</li>
									<li>HM Handel ApS</li>
									<li>Tømrer Henning Mastrup</li>
									<li>Tømrer Hein Christiansen</li>
									<li>Tømrer B. & T. Christensen</li>
									<li>Weekend Slagteren</li>
									<li>Ahlmanns Blomster</li>
									<li>Flügger Farver Glumsø</li>
									<li>Glumsø Apotek</li>
									<li>Glumsø Bageri</li>
									<li>Glumsø Pizza House</li>
									<li>Gelsted Bilservice</li>
									<li>Khanna Brugskunst</li>
									<li>Kloakmester Ole Bang</li>
									<li>Mikkelsen</li>
									<li>Max Bank Næstved Storcenter</li>
									<li>Spar Nord Næstved</li>
									<li>Næstved Gulve</li>
									<li>Fætter BR i Storcentret</li>
								</ul>
							</td>
						</tr>
					</table>
				</td>
				<td width="33%" class="topped">
					<img src="images/DSC_0149_300px.jpg" width="300px" /><br/><br/>
					<img src="images/DSC_2408_300px.jpg" width="300px" /><br/><br/>
					<img src="images/DSC_0145_300px.jpg" width="300px" /><br/>
				</td>
			</tr>
		</table>
		<h5>Se flere billeder fra arrangementet <a href="https://picasaweb.google.com/mogens.engmark/KFUMSpejderneHerlufmagleSktHans2011?authkey=Gv1sRgCN6J7saCovGYhQE&feat=directlink" target="blank">HER</a></h5>
    </h4>
   	<div class="author_tag">26-6-2011 - Mogens Engmark</div>
   	<br />
   	<div class="headline lefted"><h2>Sankt Hans fest hos spejderne</h2></div>
	<h4>
		<p>Igen i &aring;r holder KFUM-Spejderne i Herlufmagle Sankt Hans fest.</p>
		<p>Vi fyrer op i <b>grillen</b> så den er klar <b>klokken 17.00</b> - I skal bare selv medbringe det der skal på den og hvad i ellers gerne vil have ved siden af (drikkevarer kan købes).</p>
		<p>Det vil v&aelig;re en god ide at tage badet&oslash;j/skiftet&oslash;j med til b&oslash;rnene, for N&aelig;stved Redningsberedskab kigger ogs&aring; forbi inden <b>b&aring;let</b> tændes <b>klokken 20.30</b></p>
		<h5>Den hustandsomdelte folder kan hentes <a href="files/SanktHansAften2011.pdf" target="blank">HER</a></h5>
    </h4>
   	<div class="author_tag">13-6-2011 - Mogens Engmark</div>
   	-->
 <?php **/ ?> 
 
</div>