<?php 
?>

<div id="page" class="page">
	<div class="headline lefted"><h2>Åbent Landbrug - 2011</h2></div>
	<h4>
		<div id="video"><iframe width="420" height="315" src="http://www.youtube.com/embed/iSmE3oE7qiU" frameborder="0"></iframe></div>
		<p>
			Søndag d. 18-9-2011 blev der afholdt Åbent Landbrug over hele landet og Herlufmagle Gruppe var igen i år med på <a href="http://www.aabentlandbrug.dk/Find_gaard/Sjaelland_og_Sydhavsoerne/Assendrup_Hovedgaard.aspx" target="blank">Assendrup Hovedgård</a>.<br /> 
			1300 mennesker trodsede vind og vejr, besøgte gårdens køer og kom "Tættere på Naturen" med vores mangfoldige aktiviteter.<br />   
			<br />
			<br />
			I år kunne vi byde på:
			<ul>
				<li>Abebro og forhindringsbane</li>
				<li>To bordfodboldbaner med 24 bigballer halm til 2x6 spillere</li>
				<li>Kraniequiz med 8 forskellige dyrekranier</li>
				<li>Knoglepuslespil – saml en ræv</li>
				<li>Gæt et gevir med opsats fra Kronhjort, Då, Rå og Sikahjort</li>
				<li>Karla Ko brændemærke på læderlap</li>
				<li>Snitteværksted på rensdyrskind</li>
				<li>Naturpuslespil med Karla Ko (se videoen til højre)</li>
				<li>Kig i et patruljetelt</li>
			</ul>
			<br />
			For os i Herlufmagle Gruppe var det en spændende dag med masser af besøg af nysgerrige børn og voksne, gode oplevelser i det fri og en masse sjov og ballade.<br />
		</p>
		<table width="100%">
			<tr>
				<td width="25%" class="topped centered"><img src="images/aaben_landbrug_DSC_1023.jpg"></td>
				<td width="25%" class="topped centered"><img src="images/aaben_landbrug_DSC_1031.jpg"></td>
				<td width="25%" class="topped centered"><img src="images/aaben_landbrug_DSC_1045.jpg"></td>
				<td width="25%" class="topped centered"><img src="images/aaben_landbrug_DSC_0033.jpg"></td>
			</tr>
		</table>
		<p>Ses vi igen til næste år?</p>
    </h4>
   	<div class="author_tag">21-9-2011 - Mogens Engmark</div>
	<div class="headline lefted"><h2>Familiespejd - en ny enhed</h2></div>
	<h4>
		<p>Den 25-9-2011 klokken 10.00 starter vi en ny enhed op i Herlufmagle Gruppe. FamilieSpejd, som denne nye enhed hedder til et tilbud til børn i alderen 3-5 år og deres familier. Så hvis friluftsliv og naturoplevelser er noget der tiltaler jer, så klæd jer på efter vejret og kig forbi.</p>
		<h5>I <a href="files/FamilieSpejd.pdf" target="blank">denne</a> folder kan du også finde lidt mere information</h5> 
    </h4>
   	<div class="author_tag">30-8-2011 - Mogens Engmark</div>
	<div class="headline lefted"><h2>Suså Idrætsdag 2011</h2></div>
	<h4>
		<p>Vejret holdt tørt og lokkede ca. 300 mennesker til Herlufmagle Hallen, som dannede ramme for Suså Idrætsdag 2011.</p>
		<p>Mange var forbi spejdernes stand og klatre på vores abebro og spille bordfodbold.</p>
		<h5>Der blev også taget en masse <a href="https://picasaweb.google.com/113933098347309535962/SusaIdrTsdag?authuser=0&authkey=Gv1sRgCLOs2IGag5bIdQ&feat=directlink" target="blank">billeder</a> og en <a href="http://www.youtube.com/watch?v=i7TdpKLQuLc" target="blank">video</a> blev det sørme også til</h5> 
    </h4>
   	<div class="author_tag">30-8-2011 - Mogens Engmark</div>
	<div class="headline lefted"><h2>Billeder fra oprykningsdagen</h2></div>
	<h4>
		<p>En skøn dag med masser af sol og glade spejdere lagde rammen for vores oprykningdag. Demos Cratos gav motion og sved på panden hos mange, og den lækre, bålstegte flæskesteg blev indtaget med velbehag.</p>
		<p>Der blev også uddelt en masse stjerner - løst regnet var der stjerner for 411 spejderår.</p>
		<h5>Der blev også taget en masse billeder - se <a href="https://picasaweb.google.com/113933098347309535962/Oprykning2011?authuser=0&authkey=Gv1sRgCNr73v_YhcHZTg&feat=directlink" target="blank">HER</a> for at (gen)opleve arrangemetet</h5> 
    </h4>
   	<div class="author_tag">28-8-2011 - Mogens Engmark</div>
	<div class="headline lefted"><h2>Oprykningsdag d. 21-8-2011 Klokken 10.00 - 15.00</h2></div>
	<h4>
		<p>En af de store traditioner i Herlufmagle Gruppe er oprykningsdagen der altid ligger 21. august. I år er det en søndag og derfor vil vi gøre lidt særligt ud af den.</p> 
		<table width="100%">
			<tr>
				<td><b>Program</b></td>
				<td width="10"></td>
				<td></td>
			</tr>
			<tr>
				<td>10.00</td>
				<td></td>
				<td>Familiegudstjenste i Herlufmagle Kirke</td>
			</tr>
			<tr>
				<td>11.00</td>
				<td></td>
				<td>Vi mødes ved hytten, velkomst</td>
			</tr>
			<tr>
				<td>11.15</td>
				<td></td>
				<td>Demos Cratos - Spillet som Seniorspejderne udviklede sammen med tuneserne til SEE20:10</td>
			</tr>
			<tr>
				<td>13.00</td>
				<td></td>
				<td>Bålmad til alle (30,- kroner pr. pers. incl. sodavand - betales på dagen)</td>
			</tr>
			<tr>
				<td>14.15</td>
				<td></td>
				<td>Oprykningscerimoni og uddeling af Årsstjerner</td>
			</tr>
			<tr>
				<td>15.00</td>
				<td></td>
				<td>Tak for i dag.</td>
			</tr>
		</table>
		<p>Der er ingen tilmelding til oprykningsdagen – mød blot frem. Vil I være med til at spise bålmad, betaler I blot på dagen.</p>
		<h3 class="centered"><b>HUSK</b> at kun de medlemmer der personligt møder frem <b>kl. 14.15 – 15.00</b> får overrakt årsstjerner til uniformen.</h3>
		
		
		<h5>Programmet for den store dag kan hentes <a href="files/Oprykning2011.pdf" target="blank">HER</a></h5> 
    </h4>
   	<div class="author_tag">3-8-2011 - Mogens Engmark</div>
   	<br />
    <div class="headline lefted"><h2>Nyt nyhedsbrev er ude</h2></div>
	<h4>
		<p>Vores gruppeleder har begået et nyt nyhedsbrev. Læs de seneste nyheder og se lidt om hvad der skal ske det næste stykke tid.</p> 
		<h5>Det kan hentes <a href="files/NyhedsbrevAugust2011.pdf" target="blank">HER</a></h5> 
    </h4>
   	<div class="author_tag">3-8-2011 - Mogens Engmark</div>
   	<br />
    <div class="headline lefted"><h2>Ulvenes heks blev sendt til Bloksbjerg</h2></div>
   	<h4>
		<table>
			<tr>
				<td>
					<p>Trods truende skyer og byger fandt mange vej til spejdergrunden med medbragt mad og godt humør. Næstved Brand og Redning lavede skumbad til alle der havde lyst, og igen i år kan vi takke Herlufmagle Auto for sponsering af skummet. Ved bålet lavede børnene massevis af pandekager og dejlige popcorn. Flere børn tog også udfordringen op i spejdernes vandrette bungee jump bane, hvor man bliver trukket ud i en lang cykelslange og skudt henover en presenning med vand og brun sæbe…</p>
					<p>Årets båltaler var Knud Erik Antonsen og imens knitrede bålet lystigt, hvilket var en overraskelse for mange, eftersom regnen havde høvlet ned de to foregående døgn. Men spejdere kan altså tænde bål og i løbet af kort tid røg ulvenes kunstfærdigt udførte heks til Bloksbjerg.</p>
					<p>Tak for det gode fremmøde og især en stor tak til de mange lokale erhvervsdrivende, der havde givet flotte og mange præmier til vores amerikanske lotteri:</p>
					<table width="100%">
						<tr>
							<td width="50%">
								<ul>
									<li>Alcon´s Fitness</li>
									<li>1X2 Biler</li>
									<li>Body & Soul</li>
									<li>Daglig Brugsen Gelsted</li>
									<li>Landsbyhuset</li>
									<li>Nærkøb - Buketten</li>
									<li>Wulff Auto</li>
									<li>JHF transport</li>
									<li>Bygge og anlægsentreprenør</li>
									<li>Rune Nielsen</li>
									<li>Carlssons VVS</li>
									<li>Jensen Køleteknik</li>
									<li>A/S Sjællandske Medier</li>
									<li>Fætter BR i Næstved</li>
									<li>Gitte Sass Briller</li>
									<li>Inter Sport</li>
									<li>Pingel Cykler</li>
									<li>Spejdersport</li>
									<li>Elektrogården</li>
									<li>DT Autoteknik</li>
									<li>Frugtpresse.dk</li>
									<li>Vognmand Stig Hansen</li>
									<li>El Huset Glumsø</li>
									<li>Glumsø Bogtrykkeri A/S</li>
									<li>Ib Nordmark VVS</li>
								</ul>
							</td>
							<td width="50%">
								<ul>
									<li>Wengbergs Møbler</li>
									<li>Diba</li>
									<li>Estate Mæglerne A/S</li>
									<li>Ropox</li>
									<li>Stiegs Auto</li>
									<li>Ringsted Apotek</li>
									<li>HM Handel ApS</li>
									<li>Tømrer Henning Mastrup</li>
									<li>Tømrer Hein Christiansen</li>
									<li>Tømrer B. & T. Christensen</li>
									<li>Weekend Slagteren</li>
									<li>Ahlmanns Blomster</li>
									<li>Flügger Farver Glumsø</li>
									<li>Glumsø Apotek</li>
									<li>Glumsø Bageri</li>
									<li>Glumsø Pizza House</li>
									<li>Gelsted Bilservice</li>
									<li>Khanna Brugskunst</li>
									<li>Kloakmester Ole Bang</li>
									<li>Mikkelsen</li>
									<li>Max Bank Næstved Storcenter</li>
									<li>Spar Nord Næstved</li>
									<li>Næstved Gulve</li>
									<li>Fætter BR i Storcentret</li>
								</ul>
							</td>
						</tr>
					</table>
				</td>
				<td width="33%" class="topped">
					<img src="images/DSC_0149_300px.jpg" width="300px" /><br/><br/>
					<img src="images/DSC_2408_300px.jpg" width="300px" /><br/><br/>
					<img src="images/DSC_0145_300px.jpg" width="300px" /><br/>
				</td>
			</tr>
		</table>
		<h5>Se flere billeder fra arrangementet <a href="https://picasaweb.google.com/mogens.engmark/KFUMSpejderneHerlufmagleSktHans2011?authkey=Gv1sRgCN6J7saCovGYhQE&feat=directlink" target="blank">HER</a></h5> 
    </h4>
   	<div class="author_tag">26-6-2011 - Mogens Engmark</div>
   	<br />
   	<div class="headline lefted"><h2>Sankt Hans fest hos spejderne</h2></div>
	<h4>
		<p>Igen i &aring;r holder KFUM-Spejderne i Herlufmagle Sankt Hans fest.</p>
		<p>Vi fyrer op i <b>grillen</b> så den er klar <b>klokken 17.00</b> - I skal bare selv medbringe det der skal på den og hvad i ellers gerne vil have ved siden af (drikkevarer kan købes).</p>
		<p>Det vil v&aelig;re en god ide at tage badet&oslash;j/skiftet&oslash;j med til b&oslash;rnene, for N&aelig;stved Redningsberedskab kigger ogs&aring; forbi inden <b>b&aring;let</b> tændes <b>klokken 20.30</b></p>
		<h5>Den hustandsomdelte folder kan hentes <a href="files/SanktHansAften2011.pdf" target="blank">HER</a></h5> 
    </h4>
   	<div class="author_tag">13-6-2011 - Mogens Engmark</div>
</div>