<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />  
  <title>topspejder.dk</title>
  <?php
    //-------------------------------------
    // Stylesheets
    //-------------------------------------
    $this->headLink()->appendStylesheet('/css/1140.css');
    $this->headLink()->appendStylesheet('/css/sticky_footer.css');
    $this->headLink()->appendStylesheet('/css/design.css');
    $this->headLink()->appendStylesheet('/css/jquery-ui-1.8.6.custom.css');

    //-------------------------------------
    // Javascripts
    //-------------------------------------
    $this->headScript()->appendFile('/ckeditor/ckeditor.js');
    // jQueryMenu
    $this->headScript()->appendFile('/js/jquery-1.7.1.min.js');
    $this->headScript()->appendFile('/js/jquery-ui-1.8.18.custom.min.js');
    // Media queries
    $this->headScript()->appendFile('/js/css3-mediaqueries.js');


  ?>
    <script type="text/javascript">
        window.onload = function()
        {
            //CKEDITOR.replace('Full');
            CKEDITOR.replace('pageContent',
            {
                toolbar: 'Minimum'
            });
        };
    </script>
  <?php
    echo $this->headlink();
    echo $this->headScript();
  ?>

<script type="text/javascript">
	// navigation adjustments

	(function($) {
	 	$(document).ready(function(){
                        $('#menu ul li:has(ul)').addClass('has-submenu');
		});
	})(jQuery);

</script>
<!--[if lte IE 9]><link rel="stylesheet" href="css/ie.css" type="text/css" media="screen" /><![endif]-->
</head>
<body>
    <div id="wrap">
        <div id="main" class="container">
            <div id="top" class="top row last"></div>
            <div id="header" class="header row"></div>
            <nav id="menu" class="navigation"> 
            <?php 
                echo $this->navigation()->menu()->setUlClass(''); 
            ?>
            </nav>
            <?php
            // CHECK IF WE ARE TO DISPLAY RIGHT COLUMN
            if(!empty($this->layout()->display_right))
            {
                echo "display right";
            ?>
            <div id="content" class="content span-20 last">
                <div id="breadcrumb" class="breadcrumb span-20 last"></div>
                    <?php echo $this->layout()->content; ?>
                </div>
                <div id="content_right" class="content_right span-4 last">
                    <?php echo $this->layout()->content_right; ?>
                </div>
            <?php
    
            } else {
            
            ?>
            <div id="content" class="content span-24 last">
                <?php echo $this->layout()->content; ?>
            </div>
            <?php
            
            }
            
            ?>
        </div>
    </div>
    <div id="footer" class="container">
        <div id="footer_item" class="footer span-24 last">KFUM-Spejderne, Herlufmagle Gruppe, Sletskovvej 5, 4160 Herlufmagle</div>
    </div>
</body>
</html>