<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>topspejder.dk</title>
  <?php
    //-------------------------------------
    // Stylesheets
    //-------------------------------------
    $this->headLink()->appendStylesheet('/css/screen.css', 'screen, projection');
	$this->headLink()->appendStylesheet('/css/ie.css', 'screen, projection', 'IE');
	$this->headLink()->appendStylesheet('/css/print.css', 'print');
    $this->headLink()->appendStylesheet('/css/sticky_footer.css');
	$this->headLink()->appendStylesheet('/css/design.css');
	//jQueryMenu
	$this->headlink()->appendStylesheet('/jquerymenu/jquery-ui-1.8.6.custom.css');
	$this->headlink()->appendStylesheet('/jquerymenu/jquery.ui.potato.menu.css');

	//-------------------------------------
	// Javascripts
    //-------------------------------------
	$this->headScript()->appendFile('/ckeditor/ckeditor.js');
    // jQueryMenu
    $this->headScript()->appendFile('/jquerymenu/jquery-1.4.4.min.js');
    $this->headScript()->appendFile('/jquerymenu/jquery-ui-1.8.6.custom.min.js');
    $this->headScript()->appendFile('/jquerymenu/jquery.ui.potato.menu.js');

  ?>
	<script type="text/javascript">
    window.onload = function()
    {
        //CKEDITOR.replace('Full');
        CKEDITOR.replace('pageContent',
                {
            		toolbar: 'Minimum'
                });
    };
</script>
  <?php
    echo $this->headlink();
    echo $this->headScript();
  ?>
<script>
	// navigation adjustments
	(function($) {
	 	$(document).ready(function(){
			$('ul.navigation').buttonset();
			$('ul.navigation').ptMenu();
		});
	})(jQuery);
</script>
<!--[if !IE 7]>
	<style type="text/css">
		#wrap {display:table;height:100%}
	</style>
<![endif]-->
</head>
<body>
	<div id="wrap">
		<div id="main" class="container">
			<div id="top" class="top span-24 last"></div>
			<div id="header" class="header span-24 last"></div>
			<div id="breadcrumb" class="breadcrumb span-24 last"></div>
			<div id="menu" class="menu span-24 last">
				<?php echo $this->navigation()->menu()->setUlClass('navigation'); ?>
			</div>

  			<?php
				// CHECK IF WE ARE TO DISPLAY RIGHT COLUMN
				if(!empty($this->layout()->display_right))
				{
					echo "display right";
			?>
			<div id="content" class="content span-20 last">
				<?php echo $this->layout()->content; ?>
			</div>
			<div id="content_right" class="content_right span-4 last">
				<?php echo $this->layout()->content_right; ?>
			</div>
			<?php
				} else {
			?>
			<div id="content" class="content span-24 last">
				<?php echo $this->layout()->content; ?>
			</div>
			<?php
				}
			?>
		</div>
	</div>
	<div id="footer" class="container">
		<div id="footer_item" class="footer span-24 last">KFUM-Spejderne, Herlufmagle Gruppe, Sletskovvej 5, 4160 Herlufmagle</div>
	</div>
</body>
</html>