<?php

//	echo "Dette er viewblog.phtml<br>";
//	Zend_Debug::dump($this->layout()->blogEntry);
//	$blogEntry = $this->layout()->blogEntry;
	
?>
<br><br>


<div id="blog_id_<?php echo $blogEntry['id'] ?>" class="blog_list_item">
	<div class="blog_list_item_header" >
		<div class="blog_list_item_logo span-3"><img src="../../images/unit_logos/<?php echo $blogEntry['logo']; ?>" /></div>
		<div class="blog_list_item_header_text"><h2><?php echo $blogEntry['title']; ?></h2></div>
	</div>
	<div class="blog_list_item_content"><?php echo $blogEntry['main_text'] ?></div>
	<div class="blog_list_item_footer">
		<div class="blog_list_item_author"><?php echo $blogEntry['post_date'] . " - " . $blogEntry['author']; ?></div>
	</div>
</div>
<?php 
	
?>